name: Lint YAML & Markdown

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    uses: klodr/.github/.github/workflows/reusable-lint-yaml-md.yml@63627d28c0e716176f24f06f4d3cad6c1abf3648 # main @ 2026-05-18
    with:
      markdownlint-globs: |
        **/*.md
        #CHANGELOG.md
        #node_modules
        #coverage
        #dist
